### ISSUE TITLE
Overview, seeking README.md advice, questions

### ISSUE THREAD

**Issue by cyberkoi** [snjqi188/Discourse-Ad-TM#1]
Hey all!
Team Melbourne is now working on the project plan, due mid April.
It's exciting. We've got mentors @eviltrout @SamSaffron , coaches @jocranford @adelsmee @link664 @georg and a lovely workspace! 

Now that we've moved to github and discourse for collaborative purposes, it'll be great if everyone could take a look at the README.md file (also known as project plan v1 for the ad plugin).

We reckon it'd be interesting to do. Any feedback will be most welcome. We'd love to hear from you.
Also, if there's anything else you think would be useful that we add in this repository, do shout out.

---

Ps: the rgsoc administrative team has suggested the project plan cover the following:
// It is recommended that you;
- outline the issues you will be working on
- the goals you have for these tasks
- break down how you plan to achieve said goals
- what you will be required to learn during the summer, and how you will make time for that
- why you want to work on said issues on the project.

To achieve these requirements/recommendation, we suggest you and your coach(es) contact the project mentor to discuss these issues and goals before finalising your project plan.

Submissions will be opened as of 5th of April. Until then you can simply start and continue drafting your application, then submit the application up until 14th April 23:59 UTC //

---

Thanks!

**Comment by cyberkoi** [comment]
Question about the 8 week roadmap for @eviltrout (see Roadmap.md file)
Would this 8 week course be done prior to July (prior to the official rgsoc dates), or will it span from July to August (part of the official rgsoc dates)?

**Comment by eviltrout** [comment]
I assumed you'd start when the project starts, so July would be the beginning! Or did I misunderstand and the RGSoC is only 4 weeks? If so we can scope it down :)

**Comment by cyberkoi** [comment]
@eviltrout nope you're absolutely correct! RGSoC spans about 12-14 weeks from July to September. I was unsure as to if you were hoping that we complete the 8 week roadmap prior to July, 
or that this would be done starting July (and the remaining weeks 4-6 to work on something else)

Cool, so we'll start the 8 week roadmap in July.
