### ISSUE TITLE
Pre-Study before RGSoC

### ISSUE THREAD

**Issue by cyberkoi** [snjqi188/Discourse-Ad-TM#10]
We've created a list of things to work on (in detail, on Trello) from now till 1 July. @ladydanger 

![untitled-2](https://cloud.githubusercontent.com/assets/10699989/7694235/7c4069fe-fdab-11e4-815c-404fce7dfce1.jpg)

**Comment by eviltrout** [comment]
Awesome! So excited that this is happening and you guys are ramping up to start!

**Comment by cyberkoi** [comment]
Update for Sarah's section:
![capture](https://cloud.githubusercontent.com/assets/10699989/7749700/66dd5466-ff9d-11e4-992a-cba98b549266.JPG)

**Comment by jomontanari** [comment]
@ladydanger @snjqi188 we're looking into introducing Babel at work. It's a JavaScript compiler that lets you use the new features in ES6. It might be worth having a quick read up to see if it's useful to you guys?
https://babeljs.io/
https://babeljs.io/docs/learn-es6/

**Comment by eviltrout** [comment]
We use babel at Discourse and it's amazing. I highly recommend trying it out!
