### ISSUE TITLE
consolidating an application for rgsoc

### ISSUE THREAD

**Issue by cyberkoi** [snjqi188/Discourse-Ad-TM#5]
**Questions for coaches** @georg  @link664 @adelsmee @jocranford 
We are hoping to distribute the coaches' meetup times over the weekdays, so if each coach could meet with us for 1-2hr/day, once or twice a week, that would be amazing. RGSoC would like a realistic schedule on which days and hours each coach can meet up. I'm currently creating a tentative roster so we can alter this anytime but for the moment 
- please respond with when you think you'd be happy to help! (just to get a good idea, but of course the days and times can be changed in future)
- side note, please get onto the Discourse banter if you haven't :-) https://meta.discourse.org/t/rails-girls-soc-banter/26875?u=ladydanger

**Questions for coaches and mentors**
From the past 2 weeks, Vi and I have learnt that open communication is key. 
- What are some effective ways to communicate on open source, from your experience? 
  I think it's good to have an idea on how we can handle possible situations of stress and/or conflict as a team.

**Questions for mentors** @SamSaffron @eviltrout (open to coaches as well)
It is difficult to determine our exact progress for rgsoc since we haven't begun and things will change with time. But having a plan is still helpful. Currently we have a good 8 week roadmap. I think these are realistic goals. As mentioned on the discourse banter, it would be good to have stretch goals. 

Realistic goals - 8 week road map, functioning plugin and people use it
Subordinate goals and milestones - pick up Ember, Rails by mid August (see 8 week roadmap for a week-by-week goal)
Stretch goals - adding more features for advanced functionality
- for mentors, @ladydanger and I: perhaps we could _expand on the above_
- for @ladydanger and I: we need to pick 2-3 current issues from the preferred project, explain why we chose them (with regard to skill level), explain the prospected working steps and what we expect to learn out of working on these issues.

**Other Information**
**Background information on Vi and Sarah**
Vi and I have been actively communicating since being put in touch 2-3 weeks ago. 
We've established a workspace on 271 Collins St (thanks @georg !) and look to working on the project full-time every weekday 8/9-5pm. 
Considering that our skype sessions have been going well (Sarah is currently in the States, Vi is in Melbourne), we're confident that should we work from home on some days, it will definitely be possible and not affect our performance. 

We've been discussing what's good and bad with our approaches to communicating with mentors and coaches, our skills in coding, and why we want to do the advertising plugin and work with Discourse. I can definitely foresee us continuing to maintain a two-way and constructive communication channel. 

Abit of background info,
Vi - Did a 3 month course at bloc, built a few apps.
Sarah - University student, learnt programming techniques, coding in Java, Python, mySQL, now learning C.
In general, we're both beginners to rails and javascript. But with our various skills, I think we'd complement each other well. Vi has more knowledge on business and advertising whilst I have more coding experience. We do plan on challenging ourselves with this project.

As I'm currently not in Melbourne, I had let Vi know that should there be any meetups in Melbourne (before July), she would have to be the one to do the meeting in-person, and we could only communicate online. Still, Vi was happy to work in this manner and to be a pair. I'll be back in Melbourne in July, just in time for rgsoc'15.

**Comment by eviltrout** [comment]
Here's some stretch goal ideas:
- Support for additional ad providers (easier): There are many different companies. I think the focus should be on the most popular ones first, but adding additional ones would be very useful to many people.
- Extensibility of plugin (medium difficulty): Determine what would be needed to allow others to create ad plugins on top of the ad plugin. In other words, your plugin provides the basics for showing ads, but could it be changed so that other people could add other ad providers via their own plugins for more esoteric sources?
- Support for custom banners (hard!)
  - Allow Discourse administrators to use their own chosen ads for their forum without an ad provider
  - Include basic tracking of how many impressions and click throughs the ad received

**Comment by cyberkoi** [comment]
@eviltrout this really helps! Thank you!

**Comment by jomontanari** [comment]
@ladydanger @snjqi188 

Meeting times: I'd prefer to meet up either at the start or the end of the day, if that works for you? E.g. between 8 - 10am, or after 4pm. I don't mind which days, but Monday mornings and Friday afternoons might be best avoided :) I'm on email pretty much constantly and can put time aside probably at the beginning of each day to review any questions / issues / pull requests that need a bit more thought.

Communication tools: github issues and pull requests are a good way to discuss code, I haven't used Discourse before but it looks good too. Tagging people and asking clear questions when you need a response, and also being clear about when you need a response by, is useful. 
Hangouts are good for calls / video with multiple people, Skype seems to be better but can only handle 1-1 on a free account. 
You could create a shared google calendar if you want to record meetings, deadlines, times when people are not available, etc?

In terms of your 'beyond 8 week plan' and stretch goals (keeping in mind that I've never been through the RGSOC before, so this is just from personal experience!) my advice would be not to worry too much if you don't have stretch goals set when you start, by the time you get in to the project and have more context it will be easier to decide what makes sense. Does it makes a difference for you to be accepted?

Hope that helps :)

**Comment by adelsmee** [comment]
@ladydanger @snjqi188 

Hello ladies. Good meeting times for me are Tuesday to Thursday afternoons after 2:30pm. Or Monday from 4 o'clock onwards but I think that might be a bit late for you. If we get really stuck I can probably squeeze in Friday mornings, but hopefully we can do mid-week. 

I'm also going to Bali in the first week of September, so I hope that isn't crunch time (not sure when you will be finishing?).

I like Github issues/pull requests for code discussions and am on email all day like Jo. Discourse looks good, once I get my training wheels off, as long as it will email me when I need to pay attention.

**Comment by d-natoli** [comment]
@ladydanger @snjqi188 

Meeting times for us will vary depending on what we have on during the week, but once you are in the office we can work it out. There are enough volunteers for coaches here that I'm sure we can cover you most of the week anyway.  If you need to meet up with myself or @georg before you start in July, feel free to hit us up on email and we can arrange a time.

Since you'll be in the office, if you have a daily standup at the same time each day we'll make sure one of the coaches is available to attend so that we can keep up to date with where you guys are at. 

As far as communication, github issues/PRs for feature and code discussions, discourse for everything else sounds like a good plan.

@jocranford mentioned

> Tagging people and asking clear questions when you need a response, and also being clear about when you need a response by, is useful

100% agree. With this many people communicating online, it can get a bit confusing what is being asked and who should answer it.

**Comment by cyberkoi** [comment]
@jocranford Thanks so much for the response. Good to know that there are multiple days to choose from so that gives some flexibility there. I'll just put that down in the application, but of course for the actual days and times that can be settled closer to July :) and change around when necessary.

@adelsmee That's great! Not to worry about holiday plans. We're really grateful to have you helping out. Also, thanks for listing out your free days, that gives quite some flexibility!

@link664 Right! Great advice. Thank you! We'll keep all communication channels open.

**Comment by ladydanger** [comment]
@jocranford mentioned: <blockquote>Does it makes a difference for you to be accepted?</blockquote>
Yep, it means the project will go ahead, if it doesn't I'll probably be overseas in Disneyland keeping my daughter happy :princess: (I wish there was an emoji with mickey mouse ears).Edited, sigh! even the princess emoji didn't turn up.
