### ISSUE TITLE
new project plan up

### ISSUE THREAD

**Issue by cyberkoi** [snjqi188/Discourse-Ad-TM#7]
New project-plan.md is up for all to have a look.
We've made it much more readable. Kudos to @ladydanger!

currently enquiring with rgsoc to see how coaches would have to submit statements. will get back to you with more findings.

@georg @SamSaffron @eviltrout @adelsmee @jocranford  @link664

**Comment by eviltrout** [comment]
Looks awesome so far! Quite detailed!
