### ISSUE TITLE
Coaches Response

### ISSUE THREAD

**Issue by ladydanger** [snjqi188/Discourse-Ad-TM#9]
@jocranford Hope you're doing well!  Just wanted to quickly follow up with you, we're trying to finalise our application for RGSoC before the end of tomorrow and would love to get your response in [here](https://teams.railsgirlssummerofcode.org/application_drafts/21/edit) sometime before that.  It's only one short sentence for 2 the questions - how much time am I available and why you think we'd be successful.
Cheers thanks Jo!

**Comment by jomontanari** [comment]
@ladydanger apologies, this slipped through the net (how is it April 12 already?)

**Comment by ladydanger** [comment]
Cheers thanks @jocranford! :+1:
